// Regenerates src/glyphs.generated.ts from the glyph PBFs in ./glyphs.
// The PBFs are SDF glyph ranges (openmaptiles/fonts, "Open Sans Semibold", Apache-2.0) so labels render
// without fetching fonts from the internet. Add more ranges to ./glyphs (e.g. 512-767.pbf) if needed.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";

const ranges = readdirSync("glyphs").filter(f => /^\d+-\d+\.pbf$/.test(f)).sort((a, b) => parseInt(a) - parseInt(b));
const lines = ranges.map(f => `    "${f.replace(".pbf", "")}": "${readFileSync(`glyphs/${f}`).toString("base64")}"`);
writeFileSync("src/glyphs.generated.ts",
    "// Generated by scripts/build-glyphs.mjs. Do not edit by hand.\n" +
    "export const GLYPH_RANGES: Record<string, string> = {\n" + lines.join(",\n") + "\n};\n");
console.log(`Wrote ${ranges.length} glyph ranges: ${ranges.join(", ")}`);
